use std::fs;
use std::process::Command;
use std::time::{SystemTime, UNIX_EPOCH};

fn bin() -> &'static str {
    env!("CARGO_BIN_EXE_elevate")
}

#[test]
fn cli_emits_rust_to_stdout() {
    let root = temp_dir("elevate-cli-stdout");
    let src = root.join("input.ers");
    fs::write(&src, "fn id(v: i64) -> i64 { v }\n").expect("write source should succeed");

    let output = Command::new(bin())
        .arg(&src)
        .output()
        .expect("run cli should succeed");
    assert!(output.status.success());
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("// Generated by elevate compiler."));
    assert!(stdout.contains("fn id(v: i64) -> i64"));
}

#[test]
fn cli_emits_rust_to_file() {
    let root = temp_dir("elevate-cli-file");
    let src = root.join("input.ers");
    let out = root.join("out.rs");
    fs::write(&src, "fn id(v: i64) -> i64 { v }\n").expect("write source should succeed");

    let output = Command::new(bin())
        .arg(&src)
        .arg("--emit-rust")
        .arg(&out)
        .output()
        .expect("run cli should succeed");
    assert!(output.status.success());
    let rendered = fs::read_to_string(&out).expect("output file should exist");
    assert!(rendered.contains("fn id(v: i64) -> i64"));
}

#[test]
fn cli_test_runs_discovered_test_prefixed_functions() {
    let root = temp_dir("elevate-cli-test");
    fs::create_dir_all(root.join("src")).expect("create src should succeed");
    fs::write(
        root.join("Cargo.toml"),
        "[package]\nname = \"mini\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n[lib]\nname = \"mini\"\npath = \"src/lib.rs\"\n",
    )
    .expect("write manifest should succeed");
    fs::write(
        root.join("src/lib.ers"),
        "fn test_truth() {\n    assert_eq(2 + 2, 4);\n}\n",
    )
    .expect("write source should succeed");

    let output = Command::new(bin())
        .arg("test")
        .arg(&root)
        .output()
        .expect("run cli should succeed");
    assert!(output.status.success());
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("discovered 1 test(s)"));
}

#[test]
fn cli_accepts_experiment_flags_for_compile() {
    let root = temp_dir("elevate-cli-exp");
    let src = root.join("input.ers");
    fs::write(&src, "fn id(v: i64) -> i64 { v }\n").expect("write source should succeed");

    let output = Command::new(bin())
        .arg(&src)
        .arg("--exp-infer-local-bidi")
        .output()
        .expect("run cli should succeed");
    assert!(output.status.success());
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("experimental flag enabled: exp_infer_local_bidi"));
}

fn temp_dir(prefix: &str) -> std::path::PathBuf {
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("system time should be valid")
        .as_nanos();
    let path = std::env::temp_dir().join(format!("{prefix}-{nanos}"));
    fs::create_dir_all(&path).expect("temp dir should be created");
    path
}
